# Generated by Django 5.1.3 on 2024-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(default='media/images/anonim.png', upload_to='media/images'),
        ),
    ]
