# Generated by Django 5.1.3 on 2024-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0003_users_alter_doctors_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='r_pass',
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=21, max_length=3),
        ),
    ]
