# Generated by Django 5.1.3 on 2024-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0005_userslogin_writing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='name',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
