# Generated by Django 5.1.3 on 2024-11-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0006_rename_name_writing_doctor_alter_doctors_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='object_detection.users'),
        ),
    ]
